spring:
  datasource:
    url: jdbc:h2:mem:eCommerceBackend
    #jdbc:h2:~/eCommerceBackend
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  #H2 settings
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      fail-on-empty-beans: false
